Parameters:
  sample:
    SampleVolume: 15ul
    Solution: water
  sampleAll:
    Sampleall: true
  sampleTotal:
    Diluent: water
    Solution: tartrazine
    SolutionVolume: 15ul
    TotalVolume: 150ul
  samplealone:
    SampleVolume: 20ul
    Solution: water
